### ISSUE TITLE
After two days, containers are stopped at 01:11, possibly (mistakenly) considered inactive.

### ISSUE THREAD

**Issue by january3** [bihealth/kiosc-server#142]
**Describe the bug**
After two days, containers are stopped at 01:11, possibly (mistakenly) considered inactive.

**To Reproduce**
1. Start a container.
2. Wait two days.

**Expected behavior**
Containers should be stopped after being inactive for the number of days specified in the config file.

**Comment by stolpeo** [comment]
Turned out not to be a bug but an issue with a very strict configuration. To give some context, there is a global variable which sets the maximal numbers of days for a container to stay inactive (indicated by the last proxy access from any user). This overrides the inactivity setting in the container itself when the container setting exceeds it (i.e. `min(DOCKER_CONTAINER_MAX_INACTIVITY, container.inactivity_threshold)`). `DOCKER_CONTAINER_MAX_INACTIVITY` was set to 1 day, which is of course to strict.
